### ISSUE TITLE
Generation may fail if Pick is used with nested components

### ISSUE THREAD

**Issue by AryamnovEugeniy** [DevExpress/devextreme-renovation#751]
Check what generator works wrong

- [ ] Angular
- [x] React
- [ ] Vue
- [ ] jQuery

### Declaration File

```ts
@ComponentBindings()
export class NestedProps {
  @OneWay() field1?: number;

  @Template() fieldTemplate?: () => null;

  @OneWay() field3?: number;
}

@ComponentBindings()
export class BaseProps {
  @Nested() nestedProp?: NestedProps = {};
}

export type SomeProps = BaseProps & Pick<NestedProps, 'fieldTemplate'>;

```

### Result

![image](https://user-images.githubusercontent.com/51905811/128721652-59ee0b2c-2264-4168-bc67-e4aaec560362.png)

### Additional Information

A version of the generator: 2.2.3

**Comment by MikeVitik** [comment]
Fixed in 2.3.4
